# Generated by Django 5.2.3 on 2025-06-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_lesson_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("cancelled_by_student", "Cancelled by Student"),
                    ("cancelled_by_teacher", "Cancelled by Teacher"),
                    ("reschedule_requested", "Reschedule Requested"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
