# Generated by Django 5.2.3 on 2025-06-17 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_lesson_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="new_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="new_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="reschedule_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reschedule_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
