# Generated by Django 5.2.3 on 2025-06-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_lesson_new_date_lesson_new_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="progress_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
