# Generated by Django 5.2.3 on 2025-06-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_course_courselesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courselesson",
            name="content_file",
        ),
        migrations.RemoveField(
            model_name="courselesson",
            name="order",
        ),
        migrations.AddField(
            model_name="courselesson",
            name="description",
            field=models.TextField(default="None yet."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courselesson",
            name="material",
            field=models.FileField(
                blank=True, null=True, upload_to="course_materials/"
            ),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="course_videos/"),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
