# Generated by Django 5.2.3 on 2025-06-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_courselesson_content_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="courselesson",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="material",
            field=models.FileField(
                blank=True, null=True, upload_to="lesson_materials/"
            ),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="lesson_videos/"),
        ),
    ]
