# Generated by Django 5.2.3 on 2025-06-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_courseenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
